title: "[标签] 简要描述(用一句话告诉我们你做了什么)"
labels: ["#Chat", "+中文"]
body:
  - type: markdown
    attributes:
      value: |
        ## 💬 聊天记录分享
        
        感谢您分享有趣的AI聊天对话记录！
        
        > **快速指引**：
        > 1. **修改标题**：将 `[标签]` 替换为合适的分类，例如 `[编程]`, `[创意]`, `[技巧]`, `[生活]` 等
        > 2. **填写内容**：优先分享链接，如果没有链接再粘贴对话文本
        > 3. **分享亮点**：简单说明这次对话的价值所在
        
        当然了，这只是一个模版而已，你可以自由发挥。

  - type: textarea
    id: inspiration
    attributes:
      label: "⭐ 灵光一闪"
      description: "你是怎么想到这个点子的？这个对话是用来干嘛的呢？什么地方很有趣呢？快告诉我们吧~"
      placeholder: "分享你的创意灵感和这次对话的背景..."
    validations:
      required: true

  - type: input
    id: share_link
    attributes:
      label: "🔗 分享链接"
      description: "如果有聊天记录的分享链接，请在这里提供"
      placeholder: "https://..."

  - type: textarea
    id: chat_content
    attributes:
      label: "📝 对话记录"
      description: "如果没有分享链接，请在这里粘贴对话文本"
      placeholder: "粘贴你的对话内容..."
      render: markdown


