title: "[标签] 简要描述(用一句话告诉我们这个上下文的作用)"
labels: ["#Context", "+中文"]
body:
  - type: markdown
    attributes:
      value: |
        ## ⚡ 上下文分享
        
        感谢您分享有用的上下文和背景信息！
        
        > **快速指引**：
        > 1. **修改标题**：将 `[标签]` 替换为合适的分类
        > 2. **填写内容**：提供上下文、背景或补充信息
        > 3. **分享价值**：说明这个上下文如何帮助他人
        
        当然了，这只是一个模版而已，你可以自由发挥。

  - type: textarea
    id: context_description
    attributes:
      label: "📋 上下文描述"
      description: "你要分享什么上下文或背景信息？"
      placeholder: "描述上下文、背景或补充信息..."
    validations:
      required: true

  - type: input
    id: share_link
    attributes:
      label: "🔗 分享链接"
      description: "如果有上下文分享链接，请在这里提供"
      placeholder: "https://..."

  - type: textarea
    id: context_content
    attributes:
      label: "📝 上下文内容"
      description: "请提供详细的上下文内容"
      placeholder: "在这里粘贴或编写你的上下文内容..."
      render: markdown
    validations:
      required: true
