title: "[Tag] Brief Description (Tell us what this context does in one sentence)"
labels: ["#Context", "+english"]
body:
  - type: markdown
    attributes:
      value: |
        ## ⚡ Context Sharing
        
        Thank you for sharing useful context and background information!
        
        > **Quick Guide**：
        > 1. **Modify Title**：Replace `[Tag]` with appropriate category
        > 2. **Fill Content**：Provide context, background, or supplementary information
        > 3. **Share Value**：Explain how this context helps others
        
        This is just a template, feel free to customize it.

  - type: textarea
    id: context_description
    attributes:
      label: "📋 Context Description"
      description: "What context or background information are you sharing?"
      placeholder: "Describe the context, background, or supplementary information..."
    validations:
      required: true

  - type: input
    id: share_link
    attributes:
      label: "🔗 Share Link"
      description: "If you have a context sharing link, please provide it here"
      placeholder: "https://..."

  - type: textarea
    id: context_content
    attributes:
      label: "📝 Context Content"
      description: "Please provide the detailed context content"
      placeholder: "Paste or write your context content here..."
      render: markdown
    validations:
      required: true
