title: "[Tag] Brief Description (Tell us what this prompt does in one sentence)"
labels: ["#Prompt", "+english"]
body:
  - type: markdown
    attributes:
      value: |
        ## ✨ Prompts Sharing

        Thank you for sharing high-quality AI prompt templates!

        > **Quick Guide**：
        > 1. **Modify Title**：Replace `[Tag]` with appropriate category, such as `[Programming]`, `[Writing]`, `[Analysis]`, `[Creative]`, etc.
        > 2. **Fill Content**：In the Creative Source section, explain the inspiration and purpose of the prompt. In the Prompt Sharing section, paste the complete content
        > 3. **Show Effects**：If you have demo links or usage effects, feel free to share them

        This is just a template, feel free to customize it.

  - type: textarea
    id: creative_source
    attributes:
      label: "⭐ Creative Source"
      description: "How did you come up with this prompt? What problem does it solve? What makes it unique?"
      placeholder: "Share your creative inspiration and the background of this prompt..."
    validations:
      required: true

  - type: input
    id: demo_link
    attributes:
      label: "🔗 Demo Link"
      description: "If you have a demo link, please provide it here"
      placeholder: "https://..."

  - type: textarea
    id: usage_instructions
    attributes:
      label: "📋 Usage Instructions"
      description: "Briefly explain how to use this prompt, any precautions"
      placeholder: "Usage methods, precautions, applicable scenarios, etc..."

  - type: textarea
    id: prompt_content
    attributes:
      label: "💡 Prompt Content"
      description: "Please provide the complete prompt content"
      placeholder: "Paste your prompt content here..."
      render: shell
    validations:
      required: true


