title: "[Tag] Brief Description (Tell us what this prompt does in one sentence)"
labels: ["#Prompt", "+english"]
body:
  - type: markdown
    attributes:
      value: |
        ## ✨ Prompts Sharing

        Thank you for sharing high-quality AI prompt templates!

        > **Quick Guide**：
        > 1. **Modify Title**：Replace `[Tag]` with appropriate category, such as `[Programming]`, `[Writing]`, `[Analysis]`, `[Creative]`, etc.
        > 2. **Fill Content**：In the Creative Source section, explain the inspiration and purpose of the prompt. In the Prompt Sharing section, paste the complete content
        > 3. **Show Effects**：If you have demo links or usage effects, feel free to share them

        This is just a template, feel free to customize it.

  - type: textarea
    id: creative_source
    attributes:
      label: "⭐ 创意来源"
      description: "你是怎么想到这个提示词的？它解决了什么问题？有什么独特之处呢？快告诉我们吧~"
      placeholder: "分享你的创意灵感和这个提示词的背景..."
    validations:
      required: true

  - type: input
    id: demo_link
    attributes:
      label: "🔗 演示链接"
      description: "如果有演示链接，请在这里提供"
      placeholder: "https://..."

  - type: textarea
    id: usage_instructions
    attributes:
      label: "📋 使用说明"
      description: "简单说明如何使用这个提示词，有什么注意事项"
      placeholder: "使用方法、注意事项、适用场景等..."

  - type: textarea
    id: prompt_content
    attributes:
      label: "💡 提示词内容"
      description: "请提供完整的提示词内容"
      placeholder: "在这里粘贴你的提示词内容..."
      render: shell
    validations:
      required: true

  - type: dropdown
    id: category
    attributes:
      label: "🏷️ 分类标签"
      description: "选择最适合的分类"
      options:
        - "编程"
        - "写作"
        - "分析"
        - "创意"
        - "翻译"
        - "学习"
        - "工作"
        - "生活"
        - "其他"
    validations:
      required: true

  - type: dropdown
    id: difficulty
    attributes:
      label: "📊 难度等级"
      description: "这个提示词的使用难度"
      options:
        - "初级 - 简单易用"
        - "中级 - 需要一些调整"
        - "高级 - 需要深度定制"

  - type: checkboxes
    id: terms
    attributes:
      label: "确认事项"
      description: "请确认以下事项"
      options:
        - label: "我确认这个提示词是原创或已获得授权分享"
          required: true
        - label: "我同意将此内容公开分享给社区"
          required: true
