title: "[标签] 简要描述(用一句话告诉我们这个提示词的作用)"
labels: ["#Prompt", "+中文"]
body:
  - type: markdown
    attributes:
      value: |
        ## ✨ 提示词分享
        
        感谢您分享优质的AI提示词模板！
        
        > **快速指引**：
        > 1. **修改标题**：将 `[标签]` 替换为合适的分类，例如 `[编程]`, `[写作]`, `[分析]`, `[创意]` 等
        > 2. **填写内容**：在创意来源区域说明提示词的灵感和用途，在提示词分享区域粘贴完整内容
        > 3. **展示效果**：如果有演示链接或使用效果，可以一并分享
        
        当然了，这只是一个模版而已，你可以自由发挥。

  - type: textarea
    id: creative_source
    attributes:
      label: "⭐ 创意来源"
      description: "你是怎么想到这个提示词的？它解决了什么问题？有什么独特之处呢？快告诉我们吧~"
      placeholder: "分享你的创意灵感和这个提示词的背景..."
    validations:
      required: true

  - type: input
    id: demo_link
    attributes:
      label: "🔗 演示链接"
      description: "如果有演示链接，请在这里提供"
      placeholder: "https://..."

  - type: textarea
    id: usage_instructions
    attributes:
      label: "📋 使用说明"
      description: "简单说明如何使用这个提示词，有什么注意事项"
      placeholder: "使用方法、注意事项、适用场景等..."

  - type: textarea
    id: prompt_content
    attributes:
      label: "💡 提示词内容"
      description: "请提供完整的提示词内容"
      placeholder: "在这里粘贴你的提示词内容..."
      render: shell
    validations:
      required: true

  - type: dropdown
    id: category
    attributes:
      label: "🏷️ 分类标签"
      description: "选择最适合的分类"
      options:
        - "编程"
        - "写作"
        - "分析"
        - "创意"
        - "翻译"
        - "学习"
        - "工作"
        - "生活"
        - "其他"
    validations:
      required: true

  - type: dropdown
    id: difficulty
    attributes:
      label: "📊 难度等级"
      description: "这个提示词的使用难度"
      options:
        - "初级 - 简单易用"
        - "中级 - 需要一些调整"
        - "高级 - 需要深度定制"

  - type: checkboxes
    id: terms
    attributes:
      label: "确认事项"
      description: "请确认以下事项"
      options:
        - label: "我确认这个提示词是原创或已获得授权分享"
          required: true
        - label: "我同意将此内容公开分享给社区"
          required: true
