name: AI Issue Labeler

on:
  issues:
    types: [opened, edited, reopened]
  discussion:
    types: [created, edited]

permissions:
  issues: write
  contents: read

jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - name: AI Issue Labeler
        uses: Disdjj/labeler@v1.0.5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          api-key: ${{ secrets.AI_API_KEY }}
          base-url: ${{ secrets.AI_BASE_URL }}
          model: 'gpt-5-mini'
          prompt: |
            You are a GitHub Issue labeling assistant. Analyze the Issue title and body and select ALL applicable labels STRICTLY from the existing labels list. Never invent labels; never duplicate labels.

            # Workflow
            1. Detect CONTENT TYPE first by analyzing title and body content
            2. Detect LANGUAGE based on the primary language used
            3. Detect AI PLATFORM if ChatGPT, Claude, or Gemini is mentioned
            4. For chat records: detect applicable content categories
            5. For prompts: detect applicable application scenarios
            6. For feedback: detect applicable feedback categories
            7. Only select labels that exist in {existing_labels}
            8. If uncertain about any dimension, skip it rather than guessing

            ---

            Attention: 根据Issue语言选择中文或英文标签, 不需要重复的多语言的标签

            ---

            Existing Labels (existing_labels): {existing_labels}

            ---

            Title: {content_title}

            ---

            Body : {content_body}

            ---